<?php


namespace App\Admin\Forms;


use Dcat\Admin\Admin;
use Dcat\Admin\Widgets\Form;
use Dcat\EasyExcel\Excel;

/** excel导入授权
 * Class EmpowerExcelForm
 * @package App\Admin\Forms
 */
class TestQuestionExcelForm extends Form
{
    public static $js = [
        // js脚本不能直接包含初始化操作，否则页面刷新后无效
        '/js/testQuestionForm.js',
    ];

    public function render()
    {
        Admin::js(static::$js);
        return parent::render(); // TODO: Change the autogenerated stub
    }

    public function handle(array $input)
    {
        $mechanism_id=Admin::user()->id;
        $final_data = array();
//        try {
            foreach (Excel::import($input['file'])->disk('admin')->first()->toArray() as $v) {
//                $v['类型'];
//                $v['描述'];
//                $v['选项'];
//                $v['答案'];
//                $v['图案'];
                dd($v);
//                $course_id = Course::getCourseIdByCode($v['类型']);
//                $domain_id = $v['平台授权ID(在平台管理中查询)'];
//                if ((!CourseDomain::where(['course_id' => $course_id, 'domain_id' => $domain_id])->first()) && $course_id && $domain_id) {
//                    $data = array();
//                    $data['couerse_id'] = $course_id;
//                    $data['domain_id'] = $domain_id;
//                    $data['can_see'] = 0;
//                    $data['can_sale'] = 0;
//                    $final_data[] = $data;
//                }
            }
//            CourseDomain::insert($final_data);
            //导入完成删除文件
            unlink(public_path('uploads') . '/' . $input['file']);
//        } catch (\Exception $e) {
//            return $this->response()->error('导入文件数据格式不正确');
//        }
        return $this->response()->success('附件上传成功')->location('/course-domain');
    }

    /**
     * Build a form here.
     */
    public function form()
    {
        //导入excel表单
        $this->divider();
        $this->html('<a href="#" onclick="downloadTestQuestionExcel()"><img style="border:none;" src="' . config('app.url') . '/image/downloads.png"> 模板下载 </a>');
        $this->file('file');
    }
}
